import { GameObjectRegisterOptions } from './types';
import { SPRITE_ID } from './sprites';

export const GAME_OBJECT_ID = {
  AIR: 0,
  BRICK: 1,
  GRASS: 2,
  TRAMPOLINE: 3,
  ICE: 4,
  KEY: 5,
  DOOR: 6,
  SPIKES: 7,
  PORTAL_A: 8,
  PORTAL_B: 9,
} as const;

export const gameObjects: GameObjectRegisterOptions[] = [
  {
    id: GAME_OBJECT_ID.AIR,
    spriteId: SPRITE_ID.AIR,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.BRICK,
    spriteId: SPRITE_ID.BRICK,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
    hasCollision: true,
  },
  {
    id: GAME_OBJECT_ID.GRASS,
    spriteId: SPRITE_ID.GRASS,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.TRAMPOLINE,
    spriteId: SPRITE_ID.TRAMPOLINE,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
    hasCollision: true,
  },
  {
    id: GAME_OBJECT_ID.ICE,
    spriteId: SPRITE_ID.ICE,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
    hasCollision: true,
  },
  {
    id: GAME_OBJECT_ID.KEY,
    spriteId: SPRITE_ID.KEY,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.DOOR,
    spriteId: SPRITE_ID.DOOR,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.SPIKES,
    spriteId: SPRITE_ID.SPIKES,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.PORTAL_A,
    spriteId: SPRITE_ID.PORTAL_A,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
  {
    id: GAME_OBJECT_ID.PORTAL_B,
    spriteId: SPRITE_ID.PORTAL_B,
    spriteWidth: 64,
    spriteHeight: 64,
    width: 32,
    height: 32,
  },
];
